### ISSUE TITLE
Documentation Request on Calibration Function

### ISSUE THREAD

**Issue by biro-mark** [NiryoRobotics/niryo_stepper#3]
I was reading through the calibration function and I was confused on the missed step computation.
https://github.com/NiryoRobotics/niryo_stepper/blob/master/StepperController.cpp#L280

It looks like steps are counted as missed only when the encoder detects backwards motion. 
`(direction && (motor_position_steps - last_motor_position_steps < 0))`

But I would think that `<=` would be more appropriate because as steps are missed, the rotor could remain completely stationary.

Even if the arm is currently up against an obstacle, I would imagine the actual rotor's action to be like a sawtooth back and forth as it repeatedly hits the obstacle and snaps back, instead of purely backwards motion. But I see this cannot be the case according to the code since the missed step counter is reset every time the encoder detects forward motion https://github.com/NiryoRobotics/niryo_stepper/blob/master/StepperController.cpp#L287

So I must be misunderstanding something basic here and would appreciate any clarification.

**Comment by SarraELGHALI** [comment]
Hello, 
(1) if no steps are missed , the difference `(direction && (motor_position_steps - last_motor_position_steps < 0))` will be 0 , it's not possible to `<="` in this condition ,Otherwise, Calibration will not be processed. 
(2)  if the arm go forward , the miss_steps_counters remains at 0 and it starts to increase Once it "get stuck" into the zero position at robot back , the difference between encoder position and position send by the robot increase( the miss steps counter increase) . when it goes higher than `MISS_STEPS_TRESHOLD` , [https://github.com/NiryoRobotics/niryo_stepper/blob/master/StepperController.cpp#L290](url) , we declare calibration process is over. 
(3) Missed step counter is reset during the calibration because sometimes, during the calibration , the steppers miss steps so the counter will update, so the next iteration, if the motor is not stuck into an obstacle we continue the calibration  and reset the counter.
